name: Build macOS Silicon (Production)

on:
  workflow_dispatch:

jobs:
  build-macos-arm64:
    name: Build aarch64‑apple‑darwin (Production)
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust (stable + aarch64 target)
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Cache Rust build
        uses: swatinem/rust-cache@v2
        with:
          shared-key: aarch64-apple-darwin

      - name: Set up JS toolchain
        uses: ./.github/actions/setup-js

      - name: Prepare environment
        run: |
          echo "VITE_ENVIRONMENT=production" > .env
          cat .env

      - name: Install JS deps & Cap setup
        run: |
          pnpm install
          pnpm cap-setup

      - name: Build Tauri app (production)
        working-directory: apps/desktop
        run: |
          pnpm tauri build \
            --config src-tauri/tauri.prod.conf.json \
            --target aarch64-apple-darwin
        env:
          RUST_TARGET_TRIPLE: aarch64-apple-darwin

      - name: Upload macOS‑Silicon Production DMG
        uses: actions/upload-artifact@v4
        with:
          name: cap-macos-silicon-production-dmg
          path: apps/desktop/src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg
